version: '3.8'
services:
  postgres:
    image: 'postgres'
    environment:
      POSTGRES_USER: 'jupiter'
      POSTGRES_PASSWORD: '123456'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/db
    networks:
      - postgres_net

  server:
    build: .
    ports:
      - '3000:3000'
    environment:
      DB_SCHEMA: 'jupiter'
      DB_USER: 'jupiter'
      DB_PASSWORD: '123456'
      DB_HOST: postgres
    volumes:
      - .:/jupiter
      - /jupiter/node_modules
    networks:
      - postgres_net
    depends_on:
      - postgres

volumes:
  postgres:

networks:
  postgres_net:
    driver: bridge
