version: '3.8'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis:/data/redis
    networks:
      - jupiter_net

  postgres:
    image: 'postgres:alpine'
    environment:
      POSTGRES_USER: 'jupiter'
      POSTGRES_PASSWORD: '123456'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres
    networks:
      - jupiter_net

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      POSTGRES_SCHEMA: 'jupiter'
      POSTGRES_USER: 'jupiter'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      SECRET_KEY: 'JUPITER'
      SECRET_KEY_REFRESH_TOKEN: 'JUPITER_REFRESH_TOKEN'
    volumes:
      - ./src:/app/src
      - /app/node_modules
    networks:
      - jupiter_net
    depends_on:
      - postgres
      - redis

volumes:
  postgres:
  redis:

networks:
  jupiter_net:
    driver: bridge
