apiVersion: batch/v1
kind: Job
metadata:
  name: $CI_NAME-migration
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: $CI_NAME-migration
          image: $IMAGE_TAG
          command:
            - /bin/sh
            - -c
            - |
              pkill sleep
              true

          env:
            - name: NODE_ENV
              value: 'production'
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: jupiter-secret-postgres
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jupiter-secret-postgres
                  key: password
            - name: POSTGRES_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: jupiter-secret-postgres
                  key: database
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: jupiter-secret-postgres
                  key: host

        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:latest
          command:
            - '/cloud_sql_proxy'
            - '-instances=parleyhub-323409:asia-east2:jupiter-postgres=tcp:5432'
            - '-credential_file=/secrets/cloudsql/credentials.json'
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - name: $CI_NAME
              mountPath: /secrets/cloudsql
              readOnly: true

      volumes:
        - name: $CI_NAME
          secret:
            secretName: cloudsql-secret-sa
      restartPolicy: Never
