apiVersion: batch/v1
kind: Job
metadata:
  name: $CI_NAME-migration
spec:
  template:
    spec:
      containers:
        - name: $CI_NAME-migration
          image: $IMAGE_TAG
      restartPolicy: Never
