#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '📦 📦 📦'
echo 'Styling, testing and building your project before committing.'

# Check Prettier standards
echo '👮🏼‍♀️👮🏼‍♀️👮🏼‍♀️'
echo 'Check Prettier standards...'

yarn check-format ||
(
  echo '🧨 🧨 🧨'
  echo 'Prettier check failed.'

  false;
)

# Check ESLint standards
echo '👮🏼‍♀️👮🏼‍♀️👮🏼‍♀️'
echo 'Check ESLint standards...'

yarn check-lint ||
(
  echo '🧨 🧨 🧨'
  echo 'ESLint check failed.'

  false;
)

# Check TSconfig standards
echo '👮🏼‍♀️👮🏼‍♀️👮🏼‍♀️'
echo 'Check TSconfig standards...'

yarn check-types ||
(
  echo '🧨 🧨 🧨'
  echo 'Failed type check.'

  false;
)

# Unit test
echo '👮🏼‍♀️👮🏼‍♀️👮🏼‍♀️'
echo 'Testing...'

yarn test ||
(
  echo '🧨 🧨 🧨'
  echo 'Testing failed.'

  false;
)

# Building
echo '🏗️ 🏗 🏗'
echo 'Building...'

yarn build ||
(
  echo '🧨 🧨 🧨'
  echo 'Build failed.'

  false;
)

# If everything passes... Now we can commit
echo '🚀 🚀 🚀'
echo 'Committing...'
