name: Publish

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Tag Number
        id: tag
        run: echo ::set-output name=number::${GITHUB_REF/refs\/tags\//}

      - name: GCR
        run: |
          docker build -t asia.gcr.io/${{secrets.GKE_PROJECT}}/jupiter:${{steps.tag.outputs.number}} .
          gcloud auth configure-docker
          docker push asia.gcr.io/${{secrets.GKE_PROJECT}}/jupiter:${{steps.tag.outputs.number}}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Tag Number
        id: tag
        run: echo ::set-output name=number::${GITHUB_REF/refs\/tags\//}

      - name: Deploy
        run: cd k8s && bash deploy.sh
        env:
          IMAGE_TAG: asia.gcr.io/${{secrets.GKE_PROJECT}}/jupiter:${{steps.tag.outputs.number}}
          NAME_CI: jupiter
          DOMAIN: parley-hub.com
