name: Testing and bump version

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '*.*.*'

  pull_request:
    branches:
      - 'master'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn test-all

  bump:
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.PATNAME }}
          WITH_V: false
          DEFAULT_BUMP: patch
